# -*- coding: utf-8 -*-
"""Wordcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFYb7E8APLxsZ21P4iXVowXTKk-v-6Sm
"""

# Exercise 1
# author first member
# state: ongoing

# Exercise 2
# author first member
# state: ongoing

# Exercise 3
# author first member
# state: ongoing

# Exercise 4
# author second member
# state: ongoing

# Exercise 5
# author second member
# state: ongoing

# Exercise 6
# author second member
# state: ongoing

# Exercise 7
# author second member
# state: ongoing